// Code generated by protoc-gen-go.
// source: src/discovery/discovery.proto
// DO NOT EDIT!

package discovery

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MessageType int32

const (
	MessageType_JOIN_REQUEST      MessageType = 0
	MessageType_LEAVE_REQUEST     MessageType = 1
	MessageType_SNAPSHOT_REQUEST  MessageType = 2
	MessageType_WATCH_REQUEST     MessageType = 3
	MessageType_IGNORE_REQUEST    MessageType = 4
	MessageType___LAST_REQUEST    MessageType = 99
	MessageType_ERROR_RESPONSE    MessageType = 100
	MessageType_SNAPSHOT_RESPONSE MessageType = 101
)

var MessageType_name = map[int32]string{
	0:   "JOIN_REQUEST",
	1:   "LEAVE_REQUEST",
	2:   "SNAPSHOT_REQUEST",
	3:   "WATCH_REQUEST",
	4:   "IGNORE_REQUEST",
	99:  "__LAST_REQUEST",
	100: "ERROR_RESPONSE",
	101: "SNAPSHOT_RESPONSE",
}
var MessageType_value = map[string]int32{
	"JOIN_REQUEST":      0,
	"LEAVE_REQUEST":     1,
	"SNAPSHOT_REQUEST":  2,
	"WATCH_REQUEST":     3,
	"IGNORE_REQUEST":    4,
	"__LAST_REQUEST":    99,
	"ERROR_RESPONSE":    100,
	"SNAPSHOT_RESPONSE": 101,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x MessageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}

type ServiceDefinition struct {
	Host             *string `protobuf:"bytes,1,req,name=host" json:"host,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=port" json:"port,omitempty"`
	CustomData       []byte  `protobuf:"bytes,3,opt,name=custom_data" json:"custom_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ServiceDefinition) Reset()         { *this = ServiceDefinition{} }
func (this *ServiceDefinition) String() string { return proto.CompactTextString(this) }
func (*ServiceDefinition) ProtoMessage()       {}

func (this *ServiceDefinition) GetHost() string {
	if this != nil && this.Host != nil {
		return *this.Host
	}
	return ""
}

func (this *ServiceDefinition) GetPort() int32 {
	if this != nil && this.Port != nil {
		return *this.Port
	}
	return 0
}

func (this *ServiceDefinition) GetCustomData() []byte {
	if this != nil {
		return this.CustomData
	}
	return nil
}

type JoinRequest struct {
	Group            *string            `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Service          *ServiceDefinition `protobuf:"bytes,2,req,name=service" json:"service,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *JoinRequest) Reset()         { *this = JoinRequest{} }
func (this *JoinRequest) String() string { return proto.CompactTextString(this) }
func (*JoinRequest) ProtoMessage()       {}

func (this *JoinRequest) GetGroup() string {
	if this != nil && this.Group != nil {
		return *this.Group
	}
	return ""
}

func (this *JoinRequest) GetService() *ServiceDefinition {
	if this != nil {
		return this.Service
	}
	return nil
}

type LeaveRequest struct {
	Group            *string            `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Service          *ServiceDefinition `protobuf:"bytes,2,req,name=service" json:"service,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *LeaveRequest) Reset()         { *this = LeaveRequest{} }
func (this *LeaveRequest) String() string { return proto.CompactTextString(this) }
func (*LeaveRequest) ProtoMessage()       {}

func (this *LeaveRequest) GetGroup() string {
	if this != nil && this.Group != nil {
		return *this.Group
	}
	return ""
}

func (this *LeaveRequest) GetService() *ServiceDefinition {
	if this != nil {
		return this.Service
	}
	return nil
}

type SnapshotRequest struct {
	Group            *string `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *SnapshotRequest) Reset()         { *this = SnapshotRequest{} }
func (this *SnapshotRequest) String() string { return proto.CompactTextString(this) }
func (*SnapshotRequest) ProtoMessage()       {}

func (this *SnapshotRequest) GetGroup() string {
	if this != nil && this.Group != nil {
		return *this.Group
	}
	return ""
}

type WatchRequest struct {
	Group            *string `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *WatchRequest) Reset()         { *this = WatchRequest{} }
func (this *WatchRequest) String() string { return proto.CompactTextString(this) }
func (*WatchRequest) ProtoMessage()       {}

func (this *WatchRequest) GetGroup() string {
	if this != nil && this.Group != nil {
		return *this.Group
	}
	return ""
}

type IgnoreRequest struct {
	Group            *string `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *IgnoreRequest) Reset()         { *this = IgnoreRequest{} }
func (this *IgnoreRequest) String() string { return proto.CompactTextString(this) }
func (*IgnoreRequest) ProtoMessage()       {}

func (this *IgnoreRequest) GetGroup() string {
	if this != nil && this.Group != nil {
		return *this.Group
	}
	return ""
}

type SnapshotResponse struct {
	Services         []*ServiceDefinition `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *SnapshotResponse) Reset()         { *this = SnapshotResponse{} }
func (this *SnapshotResponse) String() string { return proto.CompactTextString(this) }
func (*SnapshotResponse) ProtoMessage()       {}

type ErrorResponse struct {
	Description      *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ErrorResponse) Reset()         { *this = ErrorResponse{} }
func (this *ErrorResponse) String() string { return proto.CompactTextString(this) }
func (*ErrorResponse) ProtoMessage()       {}

func (this *ErrorResponse) GetDescription() string {
	if this != nil && this.Description != nil {
		return *this.Description
	}
	return ""
}

type Message struct {
	Sequence         *uint64      `protobuf:"varint,1,req,name=sequence" json:"sequence,omitempty"`
	Type             *MessageType `protobuf:"varint,2,req,name=type,enum=discovery.MessageType" json:"type,omitempty"`
	Payload          []byte       `protobuf:"bytes,3,req,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *Message) Reset()         { *this = Message{} }
func (this *Message) String() string { return proto.CompactTextString(this) }
func (*Message) ProtoMessage()       {}

func (this *Message) GetSequence() uint64 {
	if this != nil && this.Sequence != nil {
		return *this.Sequence
	}
	return 0
}

func (this *Message) GetType() MessageType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Message) GetPayload() []byte {
	if this != nil {
		return this.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("discovery.MessageType", MessageType_name, MessageType_value)
}
